version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  spring-app:
    depends_on:
      - mysqldb
    image: samimejri/alpine:1.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
               "spring.datasource.url": "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
               "spring.datasource.username": "root",
               "spring.datasource.password": "mysql"
             }'
    volumes:
         - .m2:/root/.m2
    stdin_open: true
    tty: true

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
      image: grafana/grafana
      container_name: grafana-container
      depends_on:
        - prometheus
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
       - grafana-data:/var/lib/grafana
volumes:
  db:
  grafana-data: